%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_CGG99';
M_.dynare_version = '5.3';
oo_.dynare_version = '5.3';
options_.dynare_version = '5.3';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(3,1);
M_.exo_names_tex = cell(3,1);
M_.exo_names_long = cell(3,1);
M_.exo_names(1) = {'inflation_'};
M_.exo_names_tex(1) = {'inflation\_'};
M_.exo_names_long(1) = {'inflation_'};
M_.exo_names(2) = {'demand_'};
M_.exo_names_tex(2) = {'demand\_'};
M_.exo_names_long(2) = {'demand_'};
M_.exo_names(3) = {'interest_'};
M_.exo_names_tex(3) = {'interest\_'};
M_.exo_names_long(3) = {'interest_'};
M_.endo_names = cell(24,1);
M_.endo_names_tex = cell(24,1);
M_.endo_names_long = cell(24,1);
M_.endo_names(1) = {'x'};
M_.endo_names_tex(1) = {'x'};
M_.endo_names_long(1) = {'x'};
M_.endo_names(2) = {'i'};
M_.endo_names_tex(2) = {'i'};
M_.endo_names_long(2) = {'i'};
M_.endo_names(3) = {'pi'};
M_.endo_names_tex(3) = {'pi'};
M_.endo_names_long(3) = {'pi'};
M_.endo_names(4) = {'interest'};
M_.endo_names_tex(4) = {'interest'};
M_.endo_names_long(4) = {'interest'};
M_.endo_names(5) = {'inflation'};
M_.endo_names_tex(5) = {'inflation'};
M_.endo_names_long(5) = {'inflation'};
M_.endo_names(6) = {'inflationq'};
M_.endo_names_tex(6) = {'inflationq'};
M_.endo_names_long(6) = {'inflationq'};
M_.endo_names(7) = {'outputgap'};
M_.endo_names_tex(7) = {'outputgap'};
M_.endo_names_long(7) = {'outputgap'};
M_.endo_names(8) = {'AUX_ENDO_LEAD_71'};
M_.endo_names_tex(8) = {'AUX\_ENDO\_LEAD\_71'};
M_.endo_names_long(8) = {'AUX_ENDO_LEAD_71'};
M_.endo_names(9) = {'AUX_ENDO_LEAD_75'};
M_.endo_names_tex(9) = {'AUX\_ENDO\_LEAD\_75'};
M_.endo_names_long(9) = {'AUX_ENDO_LEAD_75'};
M_.endo_names(10) = {'AUX_ENDO_LEAD_79'};
M_.endo_names_tex(10) = {'AUX\_ENDO\_LEAD\_79'};
M_.endo_names_long(10) = {'AUX_ENDO_LEAD_79'};
M_.endo_names(11) = {'AUX_ENDO_LEAD_106'};
M_.endo_names_tex(11) = {'AUX\_ENDO\_LEAD\_106'};
M_.endo_names_long(11) = {'AUX_ENDO_LEAD_106'};
M_.endo_names(12) = {'AUX_ENDO_LEAD_110'};
M_.endo_names_tex(12) = {'AUX\_ENDO\_LEAD\_110'};
M_.endo_names_long(12) = {'AUX_ENDO_LEAD_110'};
M_.endo_names(13) = {'AUX_ENDO_LEAD_114'};
M_.endo_names_tex(13) = {'AUX\_ENDO\_LEAD\_114'};
M_.endo_names_long(13) = {'AUX_ENDO_LEAD_114'};
M_.endo_names(14) = {'AUX_ENDO_LAG_2_1'};
M_.endo_names_tex(14) = {'AUX\_ENDO\_LAG\_2\_1'};
M_.endo_names_long(14) = {'AUX_ENDO_LAG_2_1'};
M_.endo_names(15) = {'AUX_ENDO_LAG_2_2'};
M_.endo_names_tex(15) = {'AUX\_ENDO\_LAG\_2\_2'};
M_.endo_names_long(15) = {'AUX_ENDO_LAG_2_2'};
M_.endo_names(16) = {'AUX_ENDO_LAG_6_1'};
M_.endo_names_tex(16) = {'AUX\_ENDO\_LAG\_6\_1'};
M_.endo_names_long(16) = {'AUX_ENDO_LAG_6_1'};
M_.endo_names(17) = {'AUX_ENDO_LAG_6_2'};
M_.endo_names_tex(17) = {'AUX\_ENDO\_LAG\_6\_2'};
M_.endo_names_long(17) = {'AUX_ENDO_LAG_6_2'};
M_.endo_names(18) = {'AUX_ENDO_LAG_6_3'};
M_.endo_names_tex(18) = {'AUX\_ENDO\_LAG\_6\_3'};
M_.endo_names_long(18) = {'AUX_ENDO_LAG_6_3'};
M_.endo_names(19) = {'AUX_ENDO_LAG_3_1'};
M_.endo_names_tex(19) = {'AUX\_ENDO\_LAG\_3\_1'};
M_.endo_names_long(19) = {'AUX_ENDO_LAG_3_1'};
M_.endo_names(20) = {'AUX_ENDO_LAG_3_2'};
M_.endo_names_tex(20) = {'AUX\_ENDO\_LAG\_3\_2'};
M_.endo_names_long(20) = {'AUX_ENDO_LAG_3_2'};
M_.endo_names(21) = {'AUX_ENDO_LAG_3_3'};
M_.endo_names_tex(21) = {'AUX\_ENDO\_LAG\_3\_3'};
M_.endo_names_long(21) = {'AUX_ENDO_LAG_3_3'};
M_.endo_names(22) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names_tex(22) = {'AUX\_ENDO\_LAG\_5\_1'};
M_.endo_names_long(22) = {'AUX_ENDO_LAG_5_1'};
M_.endo_names(23) = {'AUX_ENDO_LAG_5_2'};
M_.endo_names_tex(23) = {'AUX\_ENDO\_LAG\_5\_2'};
M_.endo_names_long(23) = {'AUX_ENDO_LAG_5_2'};
M_.endo_names(24) = {'AUX_ENDO_LAG_5_3'};
M_.endo_names_tex(24) = {'AUX\_ENDO\_LAG\_5\_3'};
M_.endo_names_long(24) = {'AUX_ENDO_LAG_5_3'};
M_.endo_partitions = struct();
M_.param_names = cell(39,1);
M_.param_names_tex = cell(39,1);
M_.param_names_long = cell(39,1);
M_.param_names(1) = {'cofintintb1'};
M_.param_names_tex(1) = {'cofintintb1'};
M_.param_names_long(1) = {'cofintintb1'};
M_.param_names(2) = {'cofintintb2'};
M_.param_names_tex(2) = {'cofintintb2'};
M_.param_names_long(2) = {'cofintintb2'};
M_.param_names(3) = {'cofintintb3'};
M_.param_names_tex(3) = {'cofintintb3'};
M_.param_names_long(3) = {'cofintintb3'};
M_.param_names(4) = {'cofintintb4'};
M_.param_names_tex(4) = {'cofintintb4'};
M_.param_names_long(4) = {'cofintintb4'};
M_.param_names(5) = {'cofintinf0'};
M_.param_names_tex(5) = {'cofintinf0'};
M_.param_names_long(5) = {'cofintinf0'};
M_.param_names(6) = {'cofintinfb1'};
M_.param_names_tex(6) = {'cofintinfb1'};
M_.param_names_long(6) = {'cofintinfb1'};
M_.param_names(7) = {'cofintinfb2'};
M_.param_names_tex(7) = {'cofintinfb2'};
M_.param_names_long(7) = {'cofintinfb2'};
M_.param_names(8) = {'cofintinfb3'};
M_.param_names_tex(8) = {'cofintinfb3'};
M_.param_names_long(8) = {'cofintinfb3'};
M_.param_names(9) = {'cofintinfb4'};
M_.param_names_tex(9) = {'cofintinfb4'};
M_.param_names_long(9) = {'cofintinfb4'};
M_.param_names(10) = {'cofintinff1'};
M_.param_names_tex(10) = {'cofintinff1'};
M_.param_names_long(10) = {'cofintinff1'};
M_.param_names(11) = {'cofintinff2'};
M_.param_names_tex(11) = {'cofintinff2'};
M_.param_names_long(11) = {'cofintinff2'};
M_.param_names(12) = {'cofintinff3'};
M_.param_names_tex(12) = {'cofintinff3'};
M_.param_names_long(12) = {'cofintinff3'};
M_.param_names(13) = {'cofintinff4'};
M_.param_names_tex(13) = {'cofintinff4'};
M_.param_names_long(13) = {'cofintinff4'};
M_.param_names(14) = {'cofintout'};
M_.param_names_tex(14) = {'cofintout'};
M_.param_names_long(14) = {'cofintout'};
M_.param_names(15) = {'cofintoutb1'};
M_.param_names_tex(15) = {'cofintoutb1'};
M_.param_names_long(15) = {'cofintoutb1'};
M_.param_names(16) = {'cofintoutb2'};
M_.param_names_tex(16) = {'cofintoutb2'};
M_.param_names_long(16) = {'cofintoutb2'};
M_.param_names(17) = {'cofintoutb3'};
M_.param_names_tex(17) = {'cofintoutb3'};
M_.param_names_long(17) = {'cofintoutb3'};
M_.param_names(18) = {'cofintoutb4'};
M_.param_names_tex(18) = {'cofintoutb4'};
M_.param_names_long(18) = {'cofintoutb4'};
M_.param_names(19) = {'cofintoutf1'};
M_.param_names_tex(19) = {'cofintoutf1'};
M_.param_names_long(19) = {'cofintoutf1'};
M_.param_names(20) = {'cofintoutf2'};
M_.param_names_tex(20) = {'cofintoutf2'};
M_.param_names_long(20) = {'cofintoutf2'};
M_.param_names(21) = {'cofintoutf3'};
M_.param_names_tex(21) = {'cofintoutf3'};
M_.param_names_long(21) = {'cofintoutf3'};
M_.param_names(22) = {'cofintoutf4'};
M_.param_names_tex(22) = {'cofintoutf4'};
M_.param_names_long(22) = {'cofintoutf4'};
M_.param_names(23) = {'cofintoutp'};
M_.param_names_tex(23) = {'cofintoutp'};
M_.param_names_long(23) = {'cofintoutp'};
M_.param_names(24) = {'cofintoutpb1'};
M_.param_names_tex(24) = {'cofintoutpb1'};
M_.param_names_long(24) = {'cofintoutpb1'};
M_.param_names(25) = {'cofintoutpb2'};
M_.param_names_tex(25) = {'cofintoutpb2'};
M_.param_names_long(25) = {'cofintoutpb2'};
M_.param_names(26) = {'cofintoutpb3'};
M_.param_names_tex(26) = {'cofintoutpb3'};
M_.param_names_long(26) = {'cofintoutpb3'};
M_.param_names(27) = {'cofintoutpb4'};
M_.param_names_tex(27) = {'cofintoutpb4'};
M_.param_names_long(27) = {'cofintoutpb4'};
M_.param_names(28) = {'cofintoutpf1'};
M_.param_names_tex(28) = {'cofintoutpf1'};
M_.param_names_long(28) = {'cofintoutpf1'};
M_.param_names(29) = {'cofintoutpf2'};
M_.param_names_tex(29) = {'cofintoutpf2'};
M_.param_names_long(29) = {'cofintoutpf2'};
M_.param_names(30) = {'cofintoutpf3'};
M_.param_names_tex(30) = {'cofintoutpf3'};
M_.param_names_long(30) = {'cofintoutpf3'};
M_.param_names(31) = {'cofintoutpf4'};
M_.param_names_tex(31) = {'cofintoutpf4'};
M_.param_names_long(31) = {'cofintoutpf4'};
M_.param_names(32) = {'std_r_'};
M_.param_names_tex(32) = {'std\_r\_'};
M_.param_names_long(32) = {'std_r_'};
M_.param_names(33) = {'std_r_quart'};
M_.param_names_tex(33) = {'std\_r\_quart'};
M_.param_names_long(33) = {'std_r_quart'};
M_.param_names(34) = {'coffispol'};
M_.param_names_tex(34) = {'coffispol'};
M_.param_names_long(34) = {'coffispol'};
M_.param_names(35) = {'theta'};
M_.param_names_tex(35) = {'theta'};
M_.param_names_long(35) = {'theta'};
M_.param_names(36) = {'sigma'};
M_.param_names_tex(36) = {'sigma'};
M_.param_names_long(36) = {'sigma'};
M_.param_names(37) = {'phi'};
M_.param_names_tex(37) = {'phi'};
M_.param_names_long(37) = {'phi'};
M_.param_names(38) = {'lambda'};
M_.param_names_tex(38) = {'lambda'};
M_.param_names_long(38) = {'lambda'};
M_.param_names(39) = {'beta'};
M_.param_names_tex(39) = {'beta'};
M_.param_names_long(39) = {'beta'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 24;
M_.param_nbr = 39;
M_.orig_endo_nbr = 7;
M_.aux_vars(1).endo_index = 8;
M_.aux_vars(1).type = 0;
M_.aux_vars(1).orig_expr = 'inflationq(1)';
M_.aux_vars(2).endo_index = 9;
M_.aux_vars(2).type = 0;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LEAD_71(1)';
M_.aux_vars(3).endo_index = 10;
M_.aux_vars(3).type = 0;
M_.aux_vars(3).orig_expr = 'AUX_ENDO_LEAD_75(1)';
M_.aux_vars(4).endo_index = 11;
M_.aux_vars(4).type = 0;
M_.aux_vars(4).orig_expr = 'outputgap(1)';
M_.aux_vars(5).endo_index = 12;
M_.aux_vars(5).type = 0;
M_.aux_vars(5).orig_expr = 'AUX_ENDO_LEAD_106(1)';
M_.aux_vars(6).endo_index = 13;
M_.aux_vars(6).type = 0;
M_.aux_vars(6).orig_expr = 'AUX_ENDO_LEAD_110(1)';
M_.aux_vars(7).endo_index = 14;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 3;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(7).orig_expr = 'pi(-1)';
M_.aux_vars(8).endo_index = 15;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 3;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(8).orig_expr = 'AUX_ENDO_LAG_2_1(-1)';
M_.aux_vars(9).endo_index = 16;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 7;
M_.aux_vars(9).orig_lead_lag = -1;
M_.aux_vars(9).orig_expr = 'outputgap(-1)';
M_.aux_vars(10).endo_index = 17;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 7;
M_.aux_vars(10).orig_lead_lag = -2;
M_.aux_vars(10).orig_expr = 'AUX_ENDO_LAG_6_1(-1)';
M_.aux_vars(11).endo_index = 18;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 7;
M_.aux_vars(11).orig_lead_lag = -3;
M_.aux_vars(11).orig_expr = 'AUX_ENDO_LAG_6_2(-1)';
M_.aux_vars(12).endo_index = 19;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 4;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(12).orig_expr = 'interest(-1)';
M_.aux_vars(13).endo_index = 20;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 4;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(13).orig_expr = 'AUX_ENDO_LAG_3_1(-1)';
M_.aux_vars(14).endo_index = 21;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 4;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(14).orig_expr = 'AUX_ENDO_LAG_3_2(-1)';
M_.aux_vars(15).endo_index = 22;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 6;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(15).orig_expr = 'inflationq(-1)';
M_.aux_vars(16).endo_index = 23;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 6;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(16).orig_expr = 'AUX_ENDO_LAG_5_1(-1)';
M_.aux_vars(17).endo_index = 24;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 6;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(17).orig_expr = 'AUX_ENDO_LAG_5_2(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 7;
M_.eq_nbr = 24;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 4;
M_.orig_maximum_endo_lead = 4;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 4;
M_.orig_maximum_lead = 4;
M_.orig_maximum_lag_with_diffs_expanded = 4;
M_.lead_lag_incidence = [
 1 17 41;
 0 18 0;
 2 19 42;
 3 20 0;
 0 21 0;
 4 22 43;
 5 23 44;
 0 24 45;
 0 25 46;
 0 26 47;
 0 27 48;
 0 28 49;
 0 29 50;
 6 30 0;
 7 31 0;
 8 32 0;
 9 33 0;
 10 34 0;
 11 35 0;
 12 36 0;
 13 37 0;
 14 38 0;
 15 39 0;
 16 40 0;]';
M_.nstatic = 2;
M_.nfwrd   = 6;
M_.npred   = 12;
M_.nboth   = 4;
M_.nsfwrd   = 10;
M_.nspred   = 16;
M_.ndynamic   = 22;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'interest' ;
  2 , 'name' , 'inflation' ;
  3 , 'name' , 'inflationq' ;
  4 , 'name' , 'outputgap' ;
  5 , 'name' , '5' ;
  6 , 'name' , 'x' ;
  7 , 'name' , 'pi' ;
};
M_.mapping.x.eqidx = [4 6 7 ];
M_.mapping.i.eqidx = [1 6 ];
M_.mapping.pi.eqidx = [2 3 6 7 ];
M_.mapping.interest.eqidx = [1 5 ];
M_.mapping.inflation.eqidx = [2 ];
M_.mapping.inflationq.eqidx = [3 5 ];
M_.mapping.outputgap.eqidx = [4 5 ];
M_.mapping.inflation_.eqidx = [7 ];
M_.mapping.demand_.eqidx = [6 ];
M_.mapping.interest_.eqidx = [5 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 3 4 6 7 14 15 16 17 18 19 20 21 22 23 24 ];
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(24, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(39, 1);
M_.endo_trends = struct('deflator', cell(24, 1), 'log_deflator', cell(24, 1), 'growth_factor', cell(24, 1), 'log_growth_factor', cell(24, 1));
M_.NNZDerivatives = [80; 0; -1; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(35) = 0.44;
theta = M_.params(35);
M_.params(38) = 0.0244;
lambda = M_.params(38);
M_.params(37) = 0.48;
phi = M_.params(37);
M_.params(36) = (-6.25);
sigma = M_.params(36);
M_.params(39) = 0.9913258983890954;
beta = M_.params(39);
M_.params(32) = 1;
std_r_ = M_.params(32);
M_.params(33) = 0.25;
std_r_quart = M_.params(33);
M_.params(34) = 0;
coffispol = M_.params(34);
M_.params(1) = 0;
cofintintb1 = M_.params(1);
M_.params(2) = 0;
cofintintb2 = M_.params(2);
M_.params(3) = 0;
cofintintb3 = M_.params(3);
M_.params(4) = 0;
cofintintb4 = M_.params(4);
M_.params(5) = 1.5;
cofintinf0 = M_.params(5);
M_.params(6) = 0;
cofintinfb1 = M_.params(6);
M_.params(7) = 0;
cofintinfb2 = M_.params(7);
M_.params(8) = 0;
cofintinfb3 = M_.params(8);
M_.params(9) = 0;
cofintinfb4 = M_.params(9);
M_.params(10) = 0;
cofintinff1 = M_.params(10);
M_.params(11) = 0;
cofintinff2 = M_.params(11);
M_.params(12) = 0;
cofintinff3 = M_.params(12);
M_.params(13) = 0;
cofintinff4 = M_.params(13);
M_.params(14) = 0.5;
cofintout = M_.params(14);
M_.params(15) = 0;
cofintoutb1 = M_.params(15);
M_.params(16) = 0;
cofintoutb2 = M_.params(16);
M_.params(17) = 0;
cofintoutb3 = M_.params(17);
M_.params(18) = 0;
cofintoutb4 = M_.params(18);
M_.params(19) = 0;
cofintoutf1 = M_.params(19);
M_.params(20) = 0;
cofintoutf2 = M_.params(20);
M_.params(21) = 0;
cofintoutf3 = M_.params(21);
M_.params(22) = 0;
cofintoutf4 = M_.params(22);
M_.params(23) = 0;
cofintoutp = M_.params(23);
M_.params(24) = 0;
cofintoutpb1 = M_.params(24);
M_.params(25) = 0;
cofintoutpb2 = M_.params(25);
M_.params(26) = 0;
cofintoutpb3 = M_.params(26);
M_.params(27) = 0;
cofintoutpb4 = M_.params(27);
M_.params(28) = 0;
cofintoutpf1 = M_.params(28);
M_.params(29) = 0;
cofintoutpf2 = M_.params(29);
M_.params(30) = 0;
cofintoutpf3 = M_.params(30);
M_.params(31) = 0;
cofintoutpf4 = M_.params(31);
M_.params(34) = 0;
coffispol = M_.params(34);
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4)^2;
M_.Sigma_e(2, 2) = (0.63)^2;


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_CGG99_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
